In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
X, y = np.arange(10).reshape((5, 2)), range(5)

In [3]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
list(y)

[0, 1, 2, 3, 4]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [6]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [7]:
y_train

[2, 0, 3]

In [8]:
X_test

array([[2, 3],
       [8, 9]])

In [9]:
y_test

[1, 4]

In [10]:
train_test_split(y, shuffle=False)

[[0, 1, 2], [3, 4]]